pub fn get_operator_nft_name() -> ByteArray {
  #"01"
}

pub fn get_general_nft_name() -> ByteArray {
  #"02"
}

pub fn get_trading_nft_name() -> ByteArray {
  #"03"
}

pub fn get_nav_nft_name() -> ByteArray {
  #"05"
}

pub fn get_vault_state_token_name() -> ByteArray {
  #"06"
}

pub fn get_deposit_state_nft_name() -> ByteArray {
  #"07"
}

pub fn get_withdraw_state_nft_name() -> ByteArray {
  #"08"
}
